// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: pkg/pb/service.proto

package pb

import (
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
	Value   string `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Uptime  string `protobuf:"bytes,4,opt,name=uptime,proto3" json:"uptime,omitempty"`
}

func (x *StorageUserRequest) Reset() {
	*x = StorageUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageUserRequest) ProtoMessage() {}

func (x *StorageUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageUserRequest.ProtoReflect.Descriptor instead.
func (*StorageUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{0}
}

func (x *StorageUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageUserRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *StorageUserRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StorageUserRequest) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

type StorageUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *StorageUserResponse) Reset() {
	*x = StorageUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorageUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageUserResponse) ProtoMessage() {}

func (x *StorageUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageUserResponse.ProtoReflect.Descriptor instead.
func (*StorageUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{1}
}

func (x *StorageUserResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CommandInfoUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userrequest *StorageUserRequest `protobuf:"bytes,1,opt,name=userrequest,proto3" json:"userrequest,omitempty"`
}

func (x *CommandInfoUserRequest) Reset() {
	*x = CommandInfoUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandInfoUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfoUserRequest) ProtoMessage() {}

func (x *CommandInfoUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfoUserRequest.ProtoReflect.Descriptor instead.
func (*CommandInfoUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{2}
}

func (x *CommandInfoUserRequest) GetUserrequest() *StorageUserRequest {
	if x != nil {
		return x.Userrequest
	}
	return nil
}

type CommandInfoUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userresponse *StorageUserResponse `protobuf:"bytes,1,opt,name=userresponse,proto3" json:"userresponse,omitempty"`
}

func (x *CommandInfoUserResponse) Reset() {
	*x = CommandInfoUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandInfoUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandInfoUserResponse) ProtoMessage() {}

func (x *CommandInfoUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandInfoUserResponse.ProtoReflect.Descriptor instead.
func (*CommandInfoUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{3}
}

func (x *CommandInfoUserResponse) GetUserresponse() *StorageUserResponse {
	if x != nil {
		return x.Userresponse
	}
	return nil
}

type CommandUptimeUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userrequest *StorageUserRequest `protobuf:"bytes,1,opt,name=userrequest,proto3" json:"userrequest,omitempty"`
}

func (x *CommandUptimeUserRequest) Reset() {
	*x = CommandUptimeUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandUptimeUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandUptimeUserRequest) ProtoMessage() {}

func (x *CommandUptimeUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandUptimeUserRequest.ProtoReflect.Descriptor instead.
func (*CommandUptimeUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{4}
}

func (x *CommandUptimeUserRequest) GetUserrequest() *StorageUserRequest {
	if x != nil {
		return x.Userrequest
	}
	return nil
}

type CommandUptimeUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userresponse *StorageUserResponse `protobuf:"bytes,1,opt,name=userresponse,proto3" json:"userresponse,omitempty"`
}

func (x *CommandUptimeUserResponse) Reset() {
	*x = CommandUptimeUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandUptimeUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandUptimeUserResponse) ProtoMessage() {}

func (x *CommandUptimeUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandUptimeUserResponse.ProtoReflect.Descriptor instead.
func (*CommandUptimeUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{5}
}

func (x *CommandUptimeUserResponse) GetUserresponse() *StorageUserResponse {
	if x != nil {
		return x.Userresponse
	}
	return nil
}

type CommandResetUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userrequest *StorageUserRequest `protobuf:"bytes,1,opt,name=userrequest,proto3" json:"userrequest,omitempty"`
}

func (x *CommandResetUserRequest) Reset() {
	*x = CommandResetUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResetUserRequest) ProtoMessage() {}

func (x *CommandResetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResetUserRequest.ProtoReflect.Descriptor instead.
func (*CommandResetUserRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{6}
}

func (x *CommandResetUserRequest) GetUserrequest() *StorageUserRequest {
	if x != nil {
		return x.Userrequest
	}
	return nil
}

type CommandResetUserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userresponse *StorageUserResponse `protobuf:"bytes,1,opt,name=userresponse,proto3" json:"userresponse,omitempty"`
}

func (x *CommandResetUserResponse) Reset() {
	*x = CommandResetUserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommandResetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResetUserResponse) ProtoMessage() {}

func (x *CommandResetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResetUserResponse.ProtoReflect.Descriptor instead.
func (*CommandResetUserResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_service_proto_rawDescGZIP(), []int{7}
}

func (x *CommandResetUserResponse) GetUserresponse() *StorageUserResponse {
	if x != nil {
		return x.Userresponse
	}
	return nil
}

var File_pkg_pb_service_proto protoreflect.FileDescriptor

var file_pkg_pb_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x12, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x6f, 0x72, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84,
	0x01, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x42, 0x0e, 0xba, 0xb9, 0x19, 0x0a, 0x0a, 0x08, 0x12, 0x04, 0x75, 0x75, 0x69, 0x64, 0x28,
	0x01, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x3a, 0x06, 0xba,
	0xb9, 0x19, 0x02, 0x08, 0x01, 0x22, 0x33, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x06, 0xba, 0xb9, 0x19, 0x02, 0x08, 0x01, 0x22, 0x62, 0x0a, 0x16, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x48, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x66,
	0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x64, 0x0a, 0x18, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x48, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x0b, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x68, 0x0a, 0x19,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x75, 0x73, 0x65,
	0x72, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x48, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x67, 0x0a, 0x18, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4b, 0x0a, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xd1, 0x02, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x66, 0x0a, 0x0b, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2a, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x61, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x6c, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x2c, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x74,
	0x69, 0x6d, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x55, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a,
	0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x2b, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x2d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_pkg_pb_service_proto_rawDescOnce sync.Once
	file_pkg_pb_service_proto_rawDescData = file_pkg_pb_service_proto_rawDesc
)

func file_pkg_pb_service_proto_rawDescGZIP() []byte {
	file_pkg_pb_service_proto_rawDescOnce.Do(func() {
		file_pkg_pb_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_service_proto_rawDescData)
	})
	return file_pkg_pb_service_proto_rawDescData
}

var file_pkg_pb_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pkg_pb_service_proto_goTypes = []interface{}{
	(*StorageUserRequest)(nil),        // 0: storageapplication.StorageUserRequest
	(*StorageUserResponse)(nil),       // 1: storageapplication.StorageUserResponse
	(*CommandInfoUserRequest)(nil),    // 2: storageapplication.CommandInfoUserRequest
	(*CommandInfoUserResponse)(nil),   // 3: storageapplication.CommandInfoUserResponse
	(*CommandUptimeUserRequest)(nil),  // 4: storageapplication.CommandUptimeUserRequest
	(*CommandUptimeUserResponse)(nil), // 5: storageapplication.CommandUptimeUserResponse
	(*CommandResetUserRequest)(nil),   // 6: storageapplication.CommandResetUserRequest
	(*CommandResetUserResponse)(nil),  // 7: storageapplication.CommandResetUserResponse
}
var file_pkg_pb_service_proto_depIdxs = []int32{
	0, // 0: storageapplication.CommandInfoUserRequest.userrequest:type_name -> storageapplication.StorageUserRequest
	1, // 1: storageapplication.CommandInfoUserResponse.userresponse:type_name -> storageapplication.StorageUserResponse
	0, // 2: storageapplication.CommandUptimeUserRequest.userrequest:type_name -> storageapplication.StorageUserRequest
	1, // 3: storageapplication.CommandUptimeUserResponse.userresponse:type_name -> storageapplication.StorageUserResponse
	0, // 4: storageapplication.CommandResetUserRequest.userrequest:type_name -> storageapplication.StorageUserRequest
	1, // 5: storageapplication.CommandResetUserResponse.userresponse:type_name -> storageapplication.StorageUserResponse
	2, // 6: storageapplication.StorageService.CommandInfo:input_type -> storageapplication.CommandInfoUserRequest
	4, // 7: storageapplication.StorageService.CommandUptime:input_type -> storageapplication.CommandUptimeUserRequest
	6, // 8: storageapplication.StorageService.CommandReset:input_type -> storageapplication.CommandResetUserRequest
	3, // 9: storageapplication.StorageService.CommandInfo:output_type -> storageapplication.CommandInfoUserResponse
	5, // 10: storageapplication.StorageService.CommandUptime:output_type -> storageapplication.CommandUptimeUserResponse
	7, // 11: storageapplication.StorageService.CommandReset:output_type -> storageapplication.CommandResetUserResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_pb_service_proto_init() }
func file_pkg_pb_service_proto_init() {
	if File_pkg_pb_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorageUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandInfoUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandInfoUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandUptimeUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandUptimeUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResetUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommandResetUserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_service_proto_goTypes,
		DependencyIndexes: file_pkg_pb_service_proto_depIdxs,
		MessageInfos:      file_pkg_pb_service_proto_msgTypes,
	}.Build()
	File_pkg_pb_service_proto = out.File
	file_pkg_pb_service_proto_rawDesc = nil
	file_pkg_pb_service_proto_goTypes = nil
	file_pkg_pb_service_proto_depIdxs = nil
}
